# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: no-commit-to-branch
  - repo: https://github.com/srstevenson/nb-clean
    rev: 2.4.0
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-outputs
          - --
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: local
    hooks:
      - id: poetry-check
        name: validate pyproject.toml
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$
      - id: poetry-lock
        name: check poetry.lock
        entry: poetry lock --check
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy --follow-imports=silent
        language: system
        pass_filenames: false
        types: [python]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]