checkpoint: 'Helsinki-NLP/opus-mt-en-fr'
source_lang: 'en'
target_lang: 'fr'
source_lang_flores: 'eng'
target_lang_flores: 'fra'
dataset: 'data/llm-bt-opus.nllb.en-fr'
only_eval: False
training_args:
  learning_rate: 0.00002
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0.01
  save_total_limit: 3
  logging_steps: 1
  num_train_epochs: 3
  fp16: True
